kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-op
  labels:
    app: rabbitmq-operator
    rabbitmq_cr: rabbitmq-op  
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
  selector:
    app: rabbitmq-operator
    rabbitmq_cr: rabbitmq-op  
