nameSuffix: -developing
commonLabels:
  app: rabbitmq-operator
  rabbitmq_cr: rabbitmq 

bases:
 - ../../base

resources:
 - namespace.yaml 
 - service.yaml

patchesStrategicMerge:
 - deployment.yaml

namespace: ns-developing 