apiVersion: scaling.queues/v1alpha
kind: RabbitMQ
metadata:
  name: rabbitmq-op
spec: 
  replicas: 3
  serviceDefinition: Internal
  configMap: rabbitmq-config        
  persistentVolume:
    name: data
    accessModes: [ "ReadWriteOnce" ]
    storageClass: "standard"
    resources:
      requests:
        storage: 1Gi
  template:
    spec:
      contaniers:
        name: rabbitmq-k8s
        image: rabbitmq:3.8.1
        imagePullPolicy: IfNotPresent 
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 15
