
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: rabbitmqs.scaling.queues
spec:
  group: scaling.queues
  names:
    kind: RabbitMQ
    listKind: RabbitMQList
    plural: rabbitmqs
    singular: rabbitmq
  scope: ""
  validation:
    openAPIV3Schema:
      description: RabbitMQ is the Schema for the rabbitmqs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RabbitMQSpec defines the desired state of RabbitMQ
          properties:
            configMap:
              type: string
            persistentVolume:
              properties:
                accessModes:
                  items:
                    type: string
                  type: array
                name:
                  type: string
                resources:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                storageClass:
                  type: string
              required:
              - accessModes
              - name
              - resources
              type: object
            replicas:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file
                Template v1.StatefulSet `json:"template"`'
              format: int32
              type: integer
            serviceDefinition:
              description: ServiceDefinition describes the service definition
              type: string
            template:
              description: TemplateSpec maps the template spec
              properties:
                spec:
                  description: ContainerSpec maps the container spec
                  properties:
                    contaniers:
                      description: ContainerDetailsSpec maps the container spec
                      properties:
                        image:
                          type: string
                        imagePullPolicy:
                          description: PullPolicy describes a policy for if/when to
                            pull a container image
                          type: string
                        livenessProbe:
                          description: CheckProbe contains the "probes" configurations
                            as livenessProbe and readinessProbe
                          properties:
                            initialDelaySeconds:
                              format: int32
                              type: integer
                            periodSeconds:
                              format: int32
                              type: integer
                            timeoutSeconds:
                              format: int32
                              type: integer
                          required:
                          - initialDelaySeconds
                          - periodSeconds
                          - timeoutSeconds
                          type: object
                        name:
                          type: string
                        readinessProbe:
                          description: CheckProbe contains the "probes" configurations
                            as livenessProbe and readinessProbe
                          properties:
                            initialDelaySeconds:
                              format: int32
                              type: integer
                            periodSeconds:
                              format: int32
                              type: integer
                            timeoutSeconds:
                              format: int32
                              type: integer
                          required:
                          - initialDelaySeconds
                          - periodSeconds
                          - timeoutSeconds
                          type: object
                      required:
                      - image
                      - imagePullPolicy
                      - livenessProbe
                      - name
                      - readinessProbe
                      type: object
                  type: object
              type: object
          required:
          - configMap
          - persistentVolume
          - replicas
          - serviceDefinition
          type: object
        status:
          description: RabbitMQStatus defines the observed state of RabbitMQ
          type: object
      type: object
  version: v1alpha
  versions:
  - name: v1alpha
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
